FROM python:3.5-slim-jessie AS builder
ARG TAVERNVER=0.5.1

RUN apt-get update \
    && apt-get --no-install-recommends --yes install wget \
    && wget https://pypi.io/packages/source/t/tavern/tavern-$TAVERNVER.tar.gz \
    && pip3 install tavern-$TAVERNVER.tar.gz[mqtt,pytest] \
    && apt-get remove wget --yes \
    && apt-get autoremove --yes \
    && apt-get clean
